"""Payoffer、Pricer与Backtester共用的稳定合同入口。"""

from runtime.protocol.version import RESOLVED_CONTRACT_SCHEMA_ID

from .contract_engine import (
    BatchPayoffEvaluation,
    Cashflow,
    ContractEvaluationCancelled,
    ContractResolutionError,
    FormulaError,
    PayoffEvaluation,
    PayoffInput,
    PreparedContractEvaluator,
    PricePath,
    ResolvedContract,
    bind_term_symbols,
    compute_monitor_values,
    evaluate_contract,
    evaluate_contract_batch,
    evaluate_formula,
    get_product,
    load_registry,
    make_payoff_input,
    overridable_term_keys,
    prepare_contract_evaluator,
    resolve_contract,
    resolve_structural_payoff_contract,
    resolve_schedule,
    resolve_schedules,
    validate_registry,
    verify_current_product_rule,
)

__all__ = (
    "BatchPayoffEvaluation",
    "Cashflow",
    "ContractEvaluationCancelled",
    "ContractResolutionError",
    "FormulaError",
    "PayoffEvaluation",
    "PayoffInput",
    "PreparedContractEvaluator",
    "PricePath",
    "ResolvedContract",
    "RESOLVED_CONTRACT_SCHEMA_ID",
    "bind_term_symbols",
    "compute_monitor_values",
    "evaluate_formula",
    "evaluate_contract",
    "evaluate_contract_batch",
    "get_product",
    "load_registry",
    "make_payoff_input",
    "overridable_term_keys",
    "prepare_contract_evaluator",
    "resolve_contract",
    "resolve_structural_payoff_contract",
    "resolve_schedule",
    "resolve_schedules",
    "validate_registry",
    "verify_current_product_rule",
)
