"""OptionHelper静态产品资料库。

本文件只保存期权自身的条款和收益路径。市场、模型、历史数据、回测控制和网页展示
均不属于OptionReg。运行期只能由共享Registry Loader读取 ``REGISTRY``，再由
``core/src/runtime/contracts/contract_engine.py``生成ResolvedContract。
"""

from __future__ import annotations


def _term(name_zh, _name_en, symbol, value_type, unit, domain):
    return {
        "name_zh": name_zh,
        "symbol": symbol,
        "value_type": value_type,
        "unit": unit,
        "domain": domain,
    }


# 观察日程只在交易日序列上取值。月度默认取当月最后一个交易日，也可指定
# 当月第1至第31个实际交易日；短月份中不存在的序号不会虚构观察日。
_OBSERVATION_SCHEDULE_DOMAIN = {
    "format": "observation_schedule",
    "selectors": [
        "daily",
        "monthly_1st", "monthly_2nd", "monthly_3rd", "monthly_4th", "monthly_5th",
        "monthly_6th", "monthly_7th", "monthly_8th", "monthly_9th", "monthly_10th",
        "monthly_11th", "monthly_12th", "monthly_13th", "monthly_14th", "monthly_15th",
        "monthly_16th", "monthly_17th", "monthly_18th", "monthly_19th", "monthly_20th",
        "monthly_21st", "monthly_22nd", "monthly_23rd", "monthly_24th", "monthly_25th",
        "monthly_26th", "monthly_27th", "monthly_28th", "monthly_29th", "monthly_30th",
        "monthly_31st", "monthly_last",
    ],
    "monthly_default": "monthly_last",
    "calendar": "trading_days_only",
}


# 键是稳定的存储键；symbol是Po、P、BT和公式解释器唯一使用的数学变量。
TERM_CATALOG = {
    "S0": _term("内部标准化起点", "Internal Normalized Base", "S_0", "number", "price", {"exclusive_min": 0}),
    "S0Vec": _term("各标的内部标准化起点", "Internal Normalized Bases", "S_{i,0}", "number_list", "price", {"exclusive_min": 0}),
    "T": _term("合同期限", "Maturity", "T", "number", "year", {"exclusive_min": 0}),
    "N": _term("内部标准化结算基准", "Internal Normalized Settlement Base", "N", "number", "normalized_point", {"exclusive_min": 0}),
    "K": _term("执行价", "Strike", "K", "number", "price", {"exclusive_min": 0}),
    "K1": _term("第一执行价", "First Strike", "K_1", "number", "price", {"exclusive_min": 0}),
    "K2": _term("第二执行价", "Second Strike", "K_2", "number", "price", {"exclusive_min": 0}),
    "K3": _term("第三执行价", "Third Strike", "K_3", "number", "price", {"exclusive_min": 0}),
    "K4": _term("第四执行价", "Fourth Strike", "K_4", "number", "price", {"exclusive_min": 0}),
    "Kp": _term("第一执行价", "First Strike", "K_1", "number", "price", {"exclusive_min": 0}),
    "Kc": _term("第二执行价", "Second Strike", "K_2", "number", "price", {"exclusive_min": 0}),
    "Kd": _term("第一执行价", "First Strike", "K_1", "number", "price", {"exclusive_min": 0}),
    "Ku": _term("第二执行价", "Second Strike", "K_2", "number", "price", {"exclusive_min": 0}),
    "Ksig": _term("执行波动率", "Variance Strike Volatility", "K", "number", "volatility", {"exclusive_min": 0}),
    "Pi_0": _term("期初期权费点数", "Initial Premium Points", "P", "number", "normalized_point", {"min": 0}),
    "P_net": _term("组合期权费净点数", "Net Option Premium Points", "P_net", "number", "normalized_point", {"min": 0}),
    "p": _term("期权费率", "Option Premium Rate", "p", "number", "rate", {"min": 0}),
    "A": _term("固定支付点数", "Fixed Payout Points", "A", "number", "normalized_point", {"min": 0}),
    "n_C": _term("看涨期权数量", "Call Quantity", "n_C", "number", "unit", {"exclusive_min": 0}),
    "n_P": _term("看跌期权数量", "Put Quantity", "n_P", "number", "unit", {"exclusive_min": 0}),
    "asset_unit": _term("资产二元交割单位", "Asset-digital Delivery Unit", "n_asset", "number", "unit", {"exclusive_min": 0}),
    "H_KO": _term("敲出障碍", "Knock-out Barrier", "H_out", "number", "price", {"exclusive_min": 0}),
    "H_KO_regular": _term("常规敲出障碍", "Regular Knock-out Barrier", "H_out_1", "number", "price", {"exclusive_min": 0}),
    "H_KO_final": _term("最后观察日敲出障碍", "Final Observation Knock-out Barrier", "H_out_2", "number", "price", {"exclusive_min": 0}),
    "H_KO_1": _term("第一敲出障碍", "First Knock-out Barrier", "H_out_1", "number", "price", {"exclusive_min": 0}),
    "H_KO_2": _term("第二敲出障碍", "Second Knock-out Barrier", "H_out_2", "number", "price", {"exclusive_min": 0}),
    "H_KI": _term("敲入障碍", "Knock-in Barrier", "H_in", "number", "price", {"exclusive_min": 0}),
    "H_KI_1": _term("第一敲入障碍", "First Knock-in Barrier", "H_in_1", "number", "price", {"exclusive_min": 0}),
    "H_KI_2": _term("第二敲入障碍", "Second Knock-in Barrier", "H_in_2", "number", "price", {"exclusive_min": 0}),
    "B": _term("气囊敲入价", "Airbag Barrier", "H_in", "number", "price", {"exclusive_min": 0}),
    "Htouch": _term("触碰障碍", "Touch Barrier", "H_touch", "number", "price", {"exclusive_min": 0}),
    "Hc": _term("派息障碍", "Coupon Barrier", "H_c", "number", "price", {"exclusive_min": 0}),
    "Hlow": _term("区间下界", "Lower Range Bound", "L", "number", "price", {"exclusive_min": 0}),
    "Hup": _term("区间上界", "Upper Range Bound", "U", "number", "price", {"exclusive_min": 0}),
    "Hfloor": _term("到期保底价格水平", "Maturity Floor Price Level", "H_floor", "number", "price", {"exclusive_min": 0}),
    "Hreset": _term("重置障碍", "Reset Barrier", "H_reset", "number", "price", {"exclusive_min": 0}),
    "Bbuf": _term("缓冲价", "Buffer Level", "K_buf", "number", "price", {"exclusive_min": 0}),
    "Lmax": _term("限损比例", "Loss Limit", "ell", "number", "rate", {"min": 0, "max": 1}),
    "F": _term("保底比例", "Floor Rate", "F", "number", "rate", {"min": 0, "max": 1}),
    "c": _term("通用票息率", "General Coupon Rate", "c", "number", "rate", {"min": 0}),
    "c_reset": _term("重置后票息", "Reset Coupon Rate", "c_reset", "number", "rate", {"min": 0}),
    "c_hedge": _term("避险票息", "Hedge Coupon Rate", "c_hedge", "number", "rate", {"min": 0}),
    "c1": _term("第一档票息", "First Coupon Rate", "c_1", "number", "rate", {"min": 0}),
    "c2": _term("第二档票息", "Second Coupon Rate", "c_2", "number", "rate", {"min": 0}),
    "c_g": _term("保底票息", "Guaranteed Coupon Rate", "c_g", "number", "rate", {"min": 0}),
    "c_e": _term("增强票息", "Enhanced Coupon Rate", "c_e", "number", "rate", {"min": 0}),
    "c_max": _term("满额票息", "Maximum Range Coupon", "c_max", "number", "rate", {"min": 0}),
    "r_out": _term("敲出固定收益", "Knock-out Fixed Return", "r_out", "number", "rate", {"min": 0}),
    "r_mat": _term("未敲出到期固定收益", "No-knock-out Maturity Return", "r_mat", "number", "rate", {"min": 0}),
    "r_cap": _term("收益上限", "Return Cap", "r_cap", "number", "rate", {"min": 0}),
    "alpha": _term("参与率", "Participation Rate", "alpha", "number", "rate", {"min": 0}),
    "alpha_u": _term("第二参与率", "Second Participation Rate", "alpha_2", "number", "rate", {"min": 0}),
    "alpha_d": _term("第一参与率", "First Participation Rate", "alpha_1", "number", "rate", {"min": 0}),
    "eta_u": _term("第二敲出补偿", "Second Knock-out Rebate", "r_out_2", "number", "rate", {"min": 0}),
    "eta_d": _term("第一敲出补偿", "First Knock-out Rebate", "r_out_1", "number", "rate", {"min": 0}),
    "eta": _term("敲出固定补偿", "Knock-out Fixed Rebate", "r_out", "number", "rate", {"min": 0}),
    "g": _term("保证金比例", "Margin Ratio", "g", "number", "rate", {
        "min": 0,
        "max": 1,
    }),
    "margin_call": _term("是否追保", "Margin Call", "margin_call", "boolean", "flag", {
        "price_term": "observation_price",
        "timing": "after_close",
        "pnl": "excluded_unless_product_cashflow",
    }),
    "Llock": _term("锁定观察期数", "Lockout Observation Count", "n_lock", "integer", "observation_count", {"min": 0}),
    "coupon_switch_observation": _term("票息档位切换观察期", "Coupon Tier Switch Observation", "n_switch", "integer", "observation_count", {"exclusive_min": 0}),
    "n_obs": _term("观察日数", "Observation Count", "n_obs", "integer", "count", {"exclusive_min": 0}),
    "q": _term("基础数量", "Base Quantity", "q", "number", "unit", {"exclusive_min": 0}),
    "m": _term("累计倍数或计息期数", "Accumulation Multiplier or Coupon Period Count", "m", "integer", "count", {"exclusive_min": 0}),
    "Nvar": _term("内部标准化方差结算基准", "Internal Normalized Variance Settlement Base", "N_V", "number", "normalized_point", {"exclusive_min": 0}),
    "Nvega": _term("内部标准化Vega基准", "Internal Normalized Vega Base", "N_Vega", "number", "normalized_point", {"exclusive_min": 0}),
    "G": _term("内部标准化保证金点数", "Internal Normalized Margin Points", "G", "number", "normalized_point", {"min": 0}),
    "annualization_days": _term("年化日数", "Annualization Days", "n_ann", "integer", "day", {"exclusive_min": 0}),
    # 未特别指定时，以交易日收盘价观察；保证金追保也以当日收盘后价格判断。
    "observation_price": _term("观察价格来源", "Observation Price Source", "observation_price", "string", "enum", {"enum": ["close", "open", "high", "low"], "default": "close"}),
    "O_KO": _term("敲出观察日程", "Knock-out Observation Schedule", "O_out", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "O_KI": _term("敲入观察日程", "Knock-in Observation Schedule", "O_in", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "Oc": _term("派息观察日程", "Coupon Observation Schedule", "O_c", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "Otouch": _term("触碰观察日程", "Touch Observation Schedule", "O_touch", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "Orange": _term("区间观察日程", "Range Observation Schedule", "O_range", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "Ovar": _term("方差观察日程", "Variance Observation Schedule", "O_var", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "Ohedge": _term("避险观察日程", "Hedge Observation Schedule", "O_hedge", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "Oreset": _term("重置观察日程", "Reset Observation Schedule", "O_reset", "string", "schedule_selector", _OBSERVATION_SCHEDULE_DOMAIN),
    "event_priority": _term("同日事件优先级", "Same-day Event Priority", "event_priority", "string", "enum", {"enum": ["KO_over_KI"]}),
    "hedge_ki_history_policy": _term("避险日敲入历史口径", "Hedge-date KI History Policy", "hedge_ki_history_policy", "string", "enum", {"enum": ["include_hedge_date", "exclude_hedge_date"]}),
    "payoff_figure_basis": _term("收益图期权费口径", "Payoff Figure Premium Basis", "payoff_figure_basis", "string", "enum", {"enum": ["gross_before_premium", "net_after_premium"]}),
    "exercise_style": _term("行权方式", "Exercise Style", "exercise_style", "string", "enum", {"enum": ["European"]}),
    "settlement": _term("结算方式", "Settlement", "settlement", "string", "enum", {"enum": ["cash"]}),
    "ko_barrier_schedule": _term("分期敲出障碍日程", "KO Barrier Schedule", "H_out_j", "schedule", "schedule", {"min_items": 1}),
    "ki_barrier_schedule": _term("分期敲入障碍日程", "KI Barrier Schedule", "H_in_j", "schedule", "schedule", {"min_items": 1}),
    "hedge_schedule": _term("避险观察日程", "Hedge Schedule", "H_hedge_j", "schedule", "schedule", {"min_items": 1}),
}


# 每个产品直接保存identity、terms、paths；不使用产品模板或继承辅助函数。
PRODUCTS = {'2.1': {'identity': {'product_id': '2.1', 'name_zh': '看涨期权', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'n_C': 1.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -n_C * P)'},
                              {'domain': 'S_T > K', 'pnl': 'cash(0, -n_C * P) + cash(T, u * n_C * (S_T - K))'}]}]},
 '2.2': {'identity': {'product_id': '2.2', 'name_zh': '看跌期权', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'n_P': 1.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T < K', 'pnl': 'cash(0, -n_P * P) + cash(T, u * n_P * (K - S_T))'},
                              {'domain': 'S_T >= K', 'pnl': 'cash(0, -n_P * P)'}]}]},
 '3.1': {'identity': {'product_id': '3.1', 'name_zh': '牛市看涨价差', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K1': 95.0,
                   'K2': 105.0,
                   'P_net': 4.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K_1', 'pnl': 'cash(0, -P_net)'},
                              {'domain': 'K_1 < S_T < K_2', 'pnl': 'cash(0, -P_net) + cash(T, u * (S_T - K_1))'},
                              {'domain': 'S_T >= K_2', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_2 - K_1))'}]}]},
 '3.2': {'identity': {'product_id': '3.2', 'name_zh': '牛市看跌价差', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K1': 95.0,
                   'K2': 105.0,
                   'P_net': 6.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K_1', 'pnl': 'cash(0, P_net) + cash(T, u * (K_1 - K_2))'},
                              {'domain': 'K_1 < S_T < K_2', 'pnl': 'cash(0, P_net) + cash(T, u * (S_T - K_2))'},
                              {'domain': 'S_T >= K_2', 'pnl': 'cash(0, P_net)'}]}]},
 '3.3': {'identity': {'product_id': '3.3', 'name_zh': '熊市看跌价差', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K1': 95.0,
                   'K2': 105.0,
                   'P_net': 4.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K_1', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_2 - K_1))'},
                              {'domain': 'K_1 < S_T < K_2', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_2 - S_T))'},
                              {'domain': 'S_T >= K_2', 'pnl': 'cash(0, -P_net)'}]}]},
 '3.4': {'identity': {'product_id': '3.4', 'name_zh': '熊市看涨价差', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K1': 95.0,
                   'K2': 105.0,
                   'P_net': 6.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K_1', 'pnl': 'cash(0, P_net)'},
                              {'domain': 'K_1 < S_T < K_2', 'pnl': 'cash(0, P_net) + cash(T, u * (K_1 - S_T))'},
                              {'domain': 'S_T >= K_2', 'pnl': 'cash(0, P_net) + cash(T, u * (K_1 - K_2))'}]}]},
 '4.1': {'identity': {'product_id': '4.1', 'name_zh': '跨式', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'P_net': 14.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T < K', 'pnl': 'cash(0, -P_net) + cash(T, u * (K - S_T))'},
                              {'domain': 'S_T == K', 'pnl': 'cash(0, -P_net)'},
                              {'domain': 'S_T > K', 'pnl': 'cash(0, -P_net) + cash(T, u * (S_T - K))'}]}]},
 '4.2': {'identity': {'product_id': '4.2', 'name_zh': '宽跨式', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'Kp': 90.0,
                   'Kc': 110.0,
                   'P_net': 8.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T < K_1', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_1 - S_T))'},
                              {'domain': 'K_1 <= S_T <= K_2', 'pnl': 'cash(0, -P_net)'},
                              {'domain': 'S_T > K_2', 'pnl': 'cash(0, -P_net) + cash(T, u * (S_T - K_2))'}]}]},
 '4.3': {'identity': {'product_id': '4.3', 'name_zh': '蝶式', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K1': 90.0,
                   'K2': 100.0,
                   'K3': 110.0,
                   'P_net': 2.5,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2 and K_2 < K_3', '2 * K_2 == K_1 + K_3']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K_1', 'pnl': 'cash(0, -P_net)'},
                              {'domain': 'K_1 < S_T <= K_2', 'pnl': 'cash(0, -P_net) + cash(T, u * (S_T - K_1))'},
                              {'domain': 'K_2 < S_T < K_3', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_3 - S_T))'},
                              {'domain': 'S_T >= K_3', 'pnl': 'cash(0, -P_net)'}]}]},
 '4.4': {'identity': {'product_id': '4.4', 'name_zh': '鹰式', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K1': 85.0,
                   'K2': 95.0,
                   'K3': 105.0,
                   'K4': 115.0,
                   'P_net': 3.0,
                   'pricing_methods': ['black_scholes', 'monte_carlo'],
                   'constraints': ['K_1 < K_2 and K_2 < K_3 and K_3 < K_4']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K_1', 'pnl': 'cash(0, -P_net)'},
                              {'domain': 'K_1 < S_T < K_2', 'pnl': 'cash(0, -P_net) + cash(T, u * (S_T - K_1))'},
                              {'domain': 'K_2 <= S_T <= K_3', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_2 - K_1))'},
                              {'domain': 'K_3 < S_T < K_4', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_2 + K_3 - K_1 - S_T))'},
                              {'domain': 'S_T >= K_4', 'pnl': 'cash(0, -P_net) + cash(T, u * (K_2 + K_3 - K_1 - K_4))'}]}]},
 '5.1': {'identity': {'product_id': '5.1', 'name_zh': '向上敲出看涨', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KO': 120.0,
                   'O_KO': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < H_out', "O_out == 'daily'"],
                   'n_C': 1.0,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out': 'first_time(S_t[O_out] >= H_out)'}},
         'paths': [{'condition': 'tau_out < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -n_C * P)'}]},
                   {'condition': 'tau_out == inf',
                    'cases': [{'domain': 'K < S_T < H_out', 'pnl': 'cash(0, -n_C * P) + cash(T, u * n_C * (S_T - K))'},
                              {'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -n_C * P)'}]}]},
 '5.2': {'identity': {'product_id': '5.2', 'name_zh': '向下敲出看涨', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KO': 88.0,
                   'O_KO': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out < K', "O_out == 'daily'"],
                   'n_C': 1.0,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out': 'first_time(S_t[O_out] <= H_out)'}},
         'paths': [{'condition': 'tau_out < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -n_C * P)'}]},
                   {'condition': 'tau_out == inf',
                    'cases': [{'domain': 'S_T > K', 'pnl': 'cash(0, -n_C * P) + cash(T, u * n_C * (S_T - K))'},
                              {'domain': 'H_out < S_T <= K', 'pnl': 'cash(0, -n_C * P)'}]}]},
 '5.3': {'identity': {'product_id': '5.3', 'name_zh': '向上敲入看涨', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KI': 120.0,
                   'O_KI': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < H_in', "O_in == 'daily'"],
                   'n_C': 1.0,
                   'monitor': {'terminal_in_observed': 'require_maturity_observation(S_t[O_in], T)',
                               'tau_in': 'first_time(S_t[O_in] >= H_in)'}},
         'paths': [{'condition': 'tau_in == inf', 'cases': [{'domain': '0 <= S_T < H_in', 'pnl': 'cash(0, -n_C * P)'}]},
                   {'condition': 'tau_in < inf',
                    'cases': [{'domain': 'S_T > K', 'pnl': 'cash(0, -n_C * P) + cash(T, u * n_C * (S_T - K))'},
                              {'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -n_C * P)'}]}]},
 '5.4': {'identity': {'product_id': '5.4', 'name_zh': '向下敲入看涨', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KI': 88.0,
                   'O_KI': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_in < K', "O_in == 'daily'"],
                   'n_C': 1.0,
                   'monitor': {'terminal_in_observed': 'require_maturity_observation(S_t[O_in], T)',
                               'tau_in': 'first_time(S_t[O_in] <= H_in)'}},
         'paths': [{'condition': 'tau_in == inf', 'cases': [{'domain': 'S_T > H_in', 'pnl': 'cash(0, -n_C * P)'}]},
                   {'condition': 'tau_in < inf',
                    'cases': [{'domain': 'S_T > K', 'pnl': 'cash(0, -n_C * P) + cash(T, u * n_C * (S_T - K))'},
                              {'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -n_C * P)'}]}]},
 '5.5': {'identity': {'product_id': '5.5', 'name_zh': '向上敲出看跌', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KO': 120.0,
                   'O_KO': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < H_out', "O_out == 'daily'"],
                   'n_P': 1.0,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out': 'first_time(S_t[O_out] >= H_out)'}},
         'paths': [{'condition': 'tau_out < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -n_P * P)'}]},
                   {'condition': 'tau_out == inf',
                    'cases': [{'domain': '0 <= S_T < K', 'pnl': 'cash(0, -n_P * P) + cash(T, u * n_P * (K - S_T))'},
                              {'domain': 'K <= S_T < H_out', 'pnl': 'cash(0, -n_P * P)'}]}]},
 '5.6': {'identity': {'product_id': '5.6', 'name_zh': '向下敲出看跌', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KO': 82.0,
                   'O_KO': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out < K', "O_out == 'daily'"],
                   'n_P': 1.0,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out': 'first_time(S_t[O_out] <= H_out)'}},
         'paths': [{'condition': 'tau_out < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -n_P * P)'}]},
                   {'condition': 'tau_out == inf',
                    'cases': [{'domain': 'H_out < S_T < K', 'pnl': 'cash(0, -n_P * P) + cash(T, u * n_P * (K - S_T))'},
                              {'domain': 'S_T >= K', 'pnl': 'cash(0, -n_P * P)'}]}]},
 '5.7': {'identity': {'product_id': '5.7', 'name_zh': '向上敲入看跌', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KI': 120.0,
                   'O_KI': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < H_in', "O_in == 'daily'"],
                   'n_P': 1.0,
                   'monitor': {'terminal_in_observed': 'require_maturity_observation(S_t[O_in], T)',
                               'tau_in': 'first_time(S_t[O_in] >= H_in)'}},
         'paths': [{'condition': 'tau_in == inf', 'cases': [{'domain': '0 <= S_T < H_in', 'pnl': 'cash(0, -n_P * P)'}]},
                   {'condition': 'tau_in < inf',
                    'cases': [{'domain': 'S_T < K', 'pnl': 'cash(0, -n_P * P) + cash(T, u * n_P * (K - S_T))'},
                              {'domain': 'S_T >= K', 'pnl': 'cash(0, -n_P * P)'}]}]},
 '5.8': {'identity': {'product_id': '5.8', 'name_zh': '向下敲入看跌', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'H_KI': 82.0,
                   'O_KI': 'daily',
                   'K': 100.0,
                   'Pi_0': 5.0,
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_in < K', "O_in == 'daily'"],
                   'n_P': 1.0,
                   'monitor': {'terminal_in_observed': 'require_maturity_observation(S_t[O_in], T)',
                               'tau_in': 'first_time(S_t[O_in] <= H_in)'}},
         'paths': [{'condition': 'tau_in == inf', 'cases': [{'domain': 'S_T > H_in', 'pnl': 'cash(0, -n_P * P)'}]},
                   {'condition': 'tau_in < inf',
                    'cases': [{'domain': 'S_T < K', 'pnl': 'cash(0, -n_P * P) + cash(T, u * n_P * (K - S_T))'},
                              {'domain': 'S_T >= K', 'pnl': 'cash(0, -n_P * P)'}]}]},
 '6.1': {'identity': {'product_id': '6.1', 'name_zh': '现金二元看涨', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'A': 20.0,
                   'Pi_0': 8.0,
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T < K', 'pnl': 'cash(0, -P)'},
                              {'domain': 'S_T >= K', 'pnl': 'cash(0, -P) + cash(T, A)'}]}]},
 '6.2': {'identity': {'product_id': '6.2', 'name_zh': '现金二元看跌', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'A': 20.0,
                   'Pi_0': 8.0,
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -P) + cash(T, A)'},
                              {'domain': 'S_T > K', 'pnl': 'cash(0, -P)'}]}]},
 '6.3': {'identity': {'product_id': '6.3', 'name_zh': '资产二元看涨', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'Pi_0': 50.0,
                   'asset_unit': 1.0,
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -P)'},
                              {'domain': 'S_T > K', 'pnl': 'cash(0, -P) + cash(T, u * n_asset * S_T)'}]}]},
 '6.4': {'identity': {'product_id': '6.4', 'name_zh': '资产二元看跌', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'exercise_style': 'European',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'K': 100.0,
                   'Pi_0': 50.0,
                   'asset_unit': 1.0,
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'True',
                    'cases': [{'domain': '0 <= S_T < K', 'pnl': 'cash(0, -P) + cash(T, u * n_asset * S_T)'},
                              {'domain': 'S_T >= K', 'pnl': 'cash(0, -P)'}]}]},
 '6.5': {'identity': {'product_id': '6.5', 'name_zh': '触碰即付', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'Htouch': 115.0,
                   'A': 20.0,
                   'Pi_0': 8.0,
                   'Otouch': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'constraints': ["O_touch == 'daily'"],
                   'monitor': {'terminal_touch_observed': 'require_maturity_observation(S_t[O_touch], T)',
                               'tau_touch': 'first_time(S_t[O_touch] >= H_touch)'},
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'tau_touch < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -P) + cash(tau_touch, A)'}]},
                   {'condition': 'tau_touch == inf', 'cases': [{'domain': '0 <= S_T < H_touch', 'pnl': 'cash(0, -P)'}]}]},
 '6.6': {'identity': {'product_id': '6.6', 'name_zh': '不碰才付', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'Htouch': 115.0,
                   'A': 20.0,
                   'Pi_0': 8.0,
                   'Otouch': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'constraints': ["O_touch == 'daily'"],
                   'monitor': {'terminal_touch_observed': 'require_maturity_observation(S_t[O_touch], T)',
                               'tau_touch': 'first_time(S_t[O_touch] >= H_touch)'},
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'tau_touch == inf',
                    'cases': [{'domain': '0 <= S_T < H_touch', 'pnl': 'cash(0, -P) + cash(T, A)'}]},
                   {'condition': 'tau_touch < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -P)'}]}]},
 '7.1': {'identity': {'product_id': '7.1', 'name_zh': '标准安全气囊Airbag', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'N': 100.0,
                   'B': 80.0,
                   'g': 0.3,
                   'p': 0.05,
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'payoff_figure_basis': 'gross_before_premium',
                   'monitor': {'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo']},
         'paths': [{'condition': 'tau_in < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -N * p) + cash(T, N * r_T)'}]},
                   {'condition': 'tau_in == inf',
                    'cases': [{'domain': 'r_T > 0', 'pnl': 'cash(0, -N * p) + cash(T, N * r_T)'},
                              {'domain': 'r_T <= 0', 'pnl': 'cash(0, -N * p)'}]}]},
 '7.2': {'identity': {'product_id': '7.2', 'name_zh': '安全气囊Airbag（上涨收益封顶）', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'N': 100.0,
                   'B': 80.0,
                   'g': 0.3,
                   'r_cap': 0.25,
                   'p': 0.0,
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                   'constraints': ['p == 0', 'r_cap > 0']},
         'paths': [{'condition': 'tau_in < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * r_T)'}]},
                   {'condition': 'tau_in == inf',
                    'cases': [{'domain': 'r_T >= r_cap', 'pnl': 'cash(T, N * r_cap)'},
                              {'domain': '0 < r_T < r_cap', 'pnl': 'cash(T, N * r_T)'},
                              {'domain': 'r_T <= 0', 'pnl': 'cash(T, 0)'}]}]},
 '7.3': {'identity': {'product_id': '7.3', 'name_zh': '安全气囊Airbag（折让上涨参与率）', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'N': 100.0,
                   'B': 80.0,
                   'g': 0.3,
                   'alpha': 0.74,
                   'p': 0.0,
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                   'constraints': ['p == 0', 'alpha > 0', 'alpha <= 1']},
         'paths': [{'condition': 'tau_in < inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * r_T)'}]},
                   {'condition': 'tau_in == inf',
                    'cases': [{'domain': 'r_T > 0', 'pnl': 'cash(T, N * alpha * r_T)'},
                              {'domain': 'r_T <= 0', 'pnl': 'cash(T, 0)'}]}]},
 '8.1': {'identity': {'product_id': '8.1', 'name_zh': '标准累购', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'K': 90.0,
                   'H_KO': 105.0,
                   'q': 100.0,
                   'm': 2,
                   'Llock': 20,
                   'n_obs': 240,
                   'O_KO': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                               'n_out': 'observation_ordinal(S_t[O_out], tau_out)',
                               'Q_acc': 'accumulated_quantity(S_t[O_out], H_out, K, q, m, n_lock, n_obs, T_contract)'},
                   'pricing_methods': ['monte_carlo'],
                   'constraints': ['K < H_out', 'n_lock <= n_obs']},
         'paths': [{'condition': 'tau_out < inf and n_out <= n_lock',
                   'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, 100 * u * Q_acc * (S_T - K) / (q * n_obs * S_0))'}]},
                   {'condition': 'tau_out < inf and n_out > n_lock',
                   'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, 100 * u * Q_acc * (S_T - K) / (q * n_obs * S_0))'}]},
                   {'condition': 'tau_out == inf',
                   'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, 100 * u * Q_acc * (S_T - K) / (q * n_obs * S_0))'}]}]},
 '9.1': {'identity': {'product_id': '9.1', 'name_zh': '经典型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.2,
                   'K': 100.0,
                   'H_KO': 103.0,
                   'H_KI': 70.0,
                   'c': 0.2,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in < H_out']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= S_0', 'pnl': 'cash(T, 0)'},
                              {'domain': '0 <= S_T < S_0', 'pnl': 'cash(T, N * r_T)'}]}]},
 '9.2': {'identity': {'product_id': '9.2', 'name_zh': 'OTM型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.2,
                   'K': 85.0,
                   'H_KO': 103.0,
                   'H_KI': 70.0,
                   'c': 0.12,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < S_0', 'H_in < H_out']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, 0)'},
                              {'domain': '0 <= S_T < K', 'pnl': 'cash(T, N * (S_T - K) / S_0)'}]}]},
 '9.3': {'identity': {'product_id': '9.3', 'name_zh': '折价OTM雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.2,
                   'K': 85.0,
                   'H_KO': 103.0,
                   'H_KI': 70.0,
                   'c': 0.14,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < S_0', 'H_in < H_out']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, 0)'},
                              {'domain': '0 <= S_T < K', 'pnl': 'cash(T, N * (S_T - K) / K)'}]}]},
 '9.4': {'identity': {'product_id': '9.4', 'name_zh': '折价建仓型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 1.0,
                   'N': 10000000.0,
                   'g': 0.3,
                   'K': 90.0,
                   'H_KO': 103.0,
                   'H_KI': 70.0,
                   'c': 0.32,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < S_0', 'H_in < H_out']},
         'paths': [{'condition': 'tau_out < tau_in',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_in < inf and tau_in <= tau_out',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * (S_T - K) / K)'}]}]},
 '9.5': {'identity': {'product_id': '9.5', 'name_zh': '超低敲入型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 1.0,
                   'H_KO': 100.0,
                   'H_KI': 65.0,
                   'c': 0.077,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'Llock': 3,
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                   'constraints': ['g == 1', 'H_in < H_out', 'is_monthly_schedule(O_out)']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * min((S_T - S_0) / S_0, 0))'}]}]},
 '9.6': {'identity': {'product_id': '9.6', 'name_zh': '超低敲入保底型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.35,
                   'H_KO': 100.0,
                   'H_KI': 65.0,
                   'c': 0.043,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'Llock': 3,
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g', 'Hfloor': 'H_in'},
                   'pricing_methods': ['monte_carlo'],
                   'constraints': ['H_in < H_out', 'is_monthly_schedule(O_out)']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= H_floor', 'pnl': 'cash(T, N * r_T)'},
                              {'domain': '0 <= S_T < H_floor', 'pnl': 'cash(T, N * (H_floor / S_0 - 1))'}]}]},
 '9.7': {'identity': {'product_id': '9.7', 'name_zh': '敲入变化型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.2,
                   'K': 100.0,
                   'H_KO': 103.0,
                   'H_KI_1': 70.0,
                   'H_KI_2': 75.0,
                   'c': 0.22,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'derived_terms': {'G': 'N * g', 'ki_barrier_schedule': '[(0, H_in_1), (1, H_in_2)]'},
                   'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                               'tau_in': "first_time_below_levels(S_t[O_in], step_levels(S_t[O_in], H_in_j, 'after'))"},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in_1 == 0.7 * S_0', 'H_in_2 == 0.75 * S_0',
                                    'H_in_1 < H_out', 'H_in_2 < H_out']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= S_0', 'pnl': 'cash(T, 0)'},
                              {'domain': '0 <= S_T < S_0', 'pnl': 'cash(T, N * r_T)'}]}]},
 '9.8': {'identity': {'product_id': '9.8', 'name_zh': '高概率敲出雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.2,
                   'H_KO': 97.0,
                   'H_KI': 80.0,
                   'c': 0.108,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'Llock': 1,
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)', 'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'derived_terms': {'G': 'N * g'},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out == 0.97 * S_0', 'H_in == 0.8 * S_0', 'is_monthly_schedule(O_out)']},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * min((S_T - S_0) / S_0, 0))'}]}]},
 '9.9': {'identity': {'product_id': '9.9', 'name_zh': '敲出递降型雪球', 'entry_status': True},
         'terms': {'S0': 100.0,
                   'T': 2.0,
                   'N': 10000000.0,
                   'g': 0.2,
                   'K': 100.0,
                   'H_KI': 70.0,
                   'c': 0.19,
                   'O_KO': 'monthly_last',
                   'O_KI': 'daily',
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                   'derived_terms': {'G': 'N * g', 'ko_barrier_schedule': '[(1, 1.03 * S_0), (2, 1.025 * S_0), (3, 1.02 * S_0), (4, 1.015 * S_0), (5, 1.01 * S_0), (6, 1.005 * S_0), (7, S_0), (8, 0.995 * S_0), (9, 0.99 * S_0), (10, 0.985 * S_0), (11, 0.98 * S_0), (12, 0.975 * S_0), (13, 0.97 * S_0), (14, 0.965 * S_0), (15, 0.96 * S_0), (16, 0.955 * S_0), (17, 0.95 * S_0), (18, 0.945 * S_0), (19, 0.94 * S_0), (20, 0.935 * S_0), (21, 0.93 * S_0), (22, 0.925 * S_0), (23, 0.92 * S_0), (24, 0.915 * S_0)]'},
                   'monitor': {'tau_out': 'first_time_levels(S_t[O_out], schedule_levels(S_t[O_out], H_out_j))',
                               'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                   'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in < 0.915 * S_0', 'T == 2', "O_out == 'monthly_last'"]},
         'paths': [{'condition': 'tau_out < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                   {'condition': 'tau_out == inf and tau_in == inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                   {'condition': 'tau_out == inf and tau_in < inf',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * min((S_T - S_0) / S_0, 0))'}]}]},
 '9.10': {'identity': {'product_id': '9.10', 'name_zh': '降落伞雪球', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO_regular': 103.0,
                    'H_KO_final': 70.0,
                    'H_KI': 70.0,
                    'c': 0.15,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'settlement': 'cash',
                    'observation_price': 'close',
                   'margin_call': True,
                    'event_priority': 'KO_over_KI',
                    'monitor': {'tau_out_1': 'first_time_before(S_t[O_out] >= H_out_1, T)',
                                'tau_out_2': 'terminal_event_time(S_t[O_out] >= H_out_2, T_contract)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_out_2 == H_in', 'H_out_2 < H_out_1']},
          'paths': [{'condition': 'tau_out_1 < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out_1, N * c * tau_out_1)'}]},
                    {'condition': 'tau_out_1 == inf and tau_out_2 < inf',
                     'cases': [{'domain': 'S_T >= H_out_2', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out_1 == inf and tau_out_2 == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out_1 == inf and tau_out_2 == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * min((S_T - S_0) / S_0, 0))'}]}]},
 '9.11': {'identity': {'product_id': '9.11', 'name_zh': '增强型雪球', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 103.0,
                    'H_KI': 70.0,
                    'c': 0.15,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'alpha': 0.5,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                                'S_out': 'first_value(S_t[O_out], S_t[O_out] >= H_out)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in < H_out']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0',
                                'pnl': 'cash(tau_out, N * (c * tau_out + alpha * (S_out - H_out) / S_0))'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= S_0', 'pnl': 'cash(T, 0)'},
                               {'domain': '0 <= S_T < S_0', 'pnl': 'cash(T, N * r_T)'}]}]},
 '9.12': {'identity': {'product_id': '9.12', 'name_zh': '票息前置型（早利）雪球', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 100.0,
                    'H_KI': 85.0,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'Llock': 0,
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'c1': 0.25,
                    'c2': 0.05,
                    'coupon_switch_observation': 12,
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)',
                                'n_out': 'observation_ordinal(S_t[O_out], tau_out)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_out == S_0', 'H_in < H_out', 'is_monthly_schedule(O_out)']},
          'paths': [{'condition': 'n_out <= n_switch',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c_1 * tau_out)'}]},
                    {'condition': 'n_switch < n_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c_2 * tau_out)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c_2 * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * min((S_T - S_0) / S_0, 0))'}]}]},
 '9.13': {'identity': {'product_id': '9.13', 'name_zh': '高保底雪球', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.5,
                    'N': 10000000.0,
                    'g': 0.05,
                    'H_KO': 103.0,
                    'H_KI': 95.0,
                    'c': 0.155,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'Llock': 1,
                   'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g', 'Hfloor': 'H_in'},
                   'pricing_methods': ['monte_carlo'],
                   'constraints': ['H_in < H_out', 'is_monthly_schedule(O_out)']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= H_floor', 'pnl': 'cash(T, N * r_T)'},
                               {'domain': '0 <= S_T < H_floor', 'pnl': 'cash(T, N * (H_floor / S_0 - 1))'}]}]},
 '9.14': {'identity': {'product_id': '9.14', 'name_zh': '救生艇雪球', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 100.0,
                    'H_KI': 80.0,
                    'c': 0.073,
                    'c_reset': 0.1,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'Oreset': 'monthly_last',
                    'settlement': 'cash',
                    'observation_price': 'close',
                   'margin_call': True,
                    'Hreset': 90.0,
                    'monitor': {'tau_in': 'first_time(S_t[O_in] <= H_in)',
                                'tau_reset': 'first_observation_on_or_after(S_t[O_reset], tau_in)',
                                'tau_out': 'reset_knockout_time(S_t[O_out], tau_reset, H_out, H_reset)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_out == S_0', 'H_in == 0.8 * S_0', 'H_reset < H_out']},
          'paths': [{'condition': 'tau_out < tau_reset',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_reset <= tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0',
                                'pnl': 'cash(tau_out, N * (c * max(tau_reset - 1 / 365, 0) + c_reset * (tau_out - max(tau_reset - 1 / 365, 0))))'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * min((S_T - S_0) / S_0, 0))'}]}]},
 '9.15': {'identity': {'product_id': '9.15', 'name_zh': '壁虎型雪球', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 103.0,
                    'H_KI': 70.0,
                    'c': 0.15,
                    'c_hedge': 0.15,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'Ohedge': 'monthly_last',
                    'hedge_ki_history_policy': 'include_hedge_date',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'hedge_schedule': [[8, 80.0], [16, 75.0]],
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)',
                                'tau_hedge_raw': 'first_time_below_schedule(S_t[O_hedge], H_hedge_j)',
                                'tau_hedge': 'effective_hedge_time(tau_hedge_raw, tau_out, tau_in, hedge_ki_history_policy)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in < H_out', 'T == 2', "O_hedge == 'monthly_last'", 'schedule_between(H_hedge_j, H_in, H_out)']},
          'paths': [{'condition': 'tau_out < inf and tau_out <= tau_hedge',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_hedge < tau_out',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_hedge, N * c_hedge * tau_hedge)'}]},
                    {'condition': 'tau_out == inf and tau_hedge == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_hedge == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= S_0', 'pnl': 'cash(T, 0)'},
                               {'domain': '0 <= S_T < S_0', 'pnl': 'cash(T, N * r_T)'}]}]},
 '9.16': {'identity': {'product_id': '9.16', 'name_zh': '期权费型小雪球（无敲入）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 100000000.0,
                    'H_KO': 103.0,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'c1': 0.0198,
                    'c2': 0.0,
                    'p': 0.01,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out == 1.03 * S_0', 'c_2 == 0']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0',
                                'pnl': 'cash(0, -N * p * T) + cash(tau_out, N * c_1 * tau_out + N * p * (T - tau_out))'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -N * p * T) + cash(T, N * c_2 * T)'}]}]},
 '9.17': {'identity': {'product_id': '9.17', 'name_zh': '全保证金型小雪球（无敲入）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 100000000.0,
                    'g': 1.0,
                    'H_KO': 103.0,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'c1': 0.065,
                    'c2': 0.0055,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['g == 1', 'H_out == 1.03 * S_0', 'c_1 == 0.065', 'c_2 == 0.0055']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c_1 * tau_out)'}]},
                    {'condition': 'tau_out == inf', 'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c_2 * T)'}]}]},
 '9.18': {'identity': {'product_id': '9.18', 'name_zh': 'Worst-Of雪球', 'entry_status': True},
          'terms': {'T': 1.0,
                    'N': 10000000.0,
                    'g': 0.3,
                    'H_KO': 103.0,
                    'H_KI': 70.0,
                    'c': 0.225,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'S0Vec': [100.0, 100.0],
                    'monitor': {'tau_out': 'first_time(W_t[O_out] >= H_out)',
                                'tau_in': 'first_time(W_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_in < H_out']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'W_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'W_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'W_T >= 100', 'pnl': 'cash(T, 0)'},
                               {'domain': '0 <= W_T < 100', 'pnl': 'cash(T, N * (W_T / 100 - 1))'}]}]},
 '9.19': {'identity': {'product_id': '9.19', 'name_zh': '凤凰式结构', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 100.0,
                    'H_KI': 80.0,
                    'c': 0.063,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'Llock': 1,
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'Hc': 80.0,
                    'Oc': 'monthly_last',
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)',
                                'n_coupon': 'count_until(S_t[O_c] >= H_c, first_time_after(S_t[O_out] >= H_out, n_lock))'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_c == H_in', 'H_in == 0.8 * S_0', 'H_out == S_0', 'T == 1', 'n_lock < 12',
                                    'is_monthly_schedule(O_out)', 'is_monthly_schedule(O_c)']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * n_coupon / 12)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * n_coupon / 12)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, N * c * n_coupon / 12)'},
                               {'domain': '0 <= S_T < K', 'pnl': 'cash(T, N * c * n_coupon / 12 + N * (S_T / K - 1))'}]}]},
 '9.20': {'identity': {'product_id': '9.20', 'name_zh': '保底凤凰式结构', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 100.0,
                    'H_KI': 75.0,
                    'c': 0.03,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'Llock': 6,
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'Hc': 75.0,
                    'Hfloor': 75.0,
                    'F': 0.75,
                    'Oc': 'monthly_last',
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)',
                                'n_coupon': 'count_until(S_t[O_c] >= H_c, first_time_after(S_t[O_out] >= H_out, n_lock))'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_c == H_in', 'H_in == H_floor', 'H_in == F * S_0', 'H_in < H_out', 'H_out == S_0', 'T == 2', 'n_lock < 24',
                                    'is_monthly_schedule(O_out)', 'is_monthly_schedule(O_c)']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * n_coupon / 12)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * n_coupon / 12)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, N * c * n_coupon / 12)'},
                               {'domain': 'F * K <= S_T < K', 'pnl': 'cash(T, N * c * n_coupon / 12 + N * (S_T / K - 1))'},
                               {'domain': '0 <= S_T < F * K', 'pnl': 'cash(T, N * c * n_coupon / 12 + N * (F - 1))'}]}]},
 '9.21': {'identity': {'product_id': '9.21', 'name_zh': 'FCN（无敲入要素）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 10000000.0,
                    'g': 0.25,
                    'K': 85.0,
                    'H_KO': 103.0,
                    'c': 0.07,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == 0.85 * S_0', 'H_out == 1.03 * S_0']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, N * c * T)'},
                               {'domain': '0 <= S_T < K', 'pnl': 'cash(T, N * c * T + N * (S_T / K - 1))'}]}]},
 '9.22': {'identity': {'product_id': '9.22', 'name_zh': 'FCN（有敲入要素）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 103.0,
                    'H_KI': 80.0,
                    'c': 0.10,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_out == 1.03 * S_0', 'H_in == 0.8 * S_0']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, N * c * T)'},
                               {'domain': '0 <= S_T < K', 'pnl': 'cash(T, N * c * T + N * (S_T / K - 1))'}]}]},
 '9.23': {'identity': {'product_id': '9.23', 'name_zh': '保底FCN（有敲入要素）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 2.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 103.0,
                    'H_KI': 80.0,
                    'c': 0.055,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'F': 0.8,
                    'Hfloor': 80.0,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in == H_floor', 'H_in == F * S_0', 'H_out == 1.03 * S_0']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * c * T)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, N * c * T)'},
                               {'domain': 'F * K <= S_T < K', 'pnl': 'cash(T, N * c * T + N * (S_T / K - 1))'},
                               {'domain': '0 <= S_T < F * K', 'pnl': 'cash(T, N * c * T + N * (F - 1))'}]}]},
 '9.24': {'identity': {'product_id': '9.24', 'name_zh': 'DCN', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'c': 0.01,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'Hc': 80.0,
                    'Oc': 'monthly_last',
                    'Llock': 3,
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= schedule_levels(S_t[O_out], H_out_j), n_lock)',
                                'n_coupon': 'count_until(S_t[O_c] >= H_c, first_time_after(S_t[O_out] >= schedule_levels(S_t[O_out], H_out_j), n_lock))'},
                    'derived_terms': {'G': 'N * g',
                                      'ko_barrier_schedule': '[(1, S_0), (2, S_0), (3, S_0), (4, S_0), (5, S_0), (6, S_0), (7, S_0), (8, S_0), (9, S_0), (10, S_0), (11, S_0), (12, 0.8 * S_0)]'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['g == 0.2', 'H_c == 0.8 * S_0', 'T == 1', 'n_lock < 12', 'is_monthly_schedule(O_out)', 'is_monthly_schedule(O_c)',
                                    'schedule_matches_ratios(H_out_j, S_0, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.8])']},
          'paths': [{'condition': 'tau_out < T',
                    'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * n_coupon)'}]},
                    {'condition': 'tau_out == T',
                     'cases': [{'domain': 'S_T >= H_c', 'pnl': 'cash(T, N * c * n_coupon)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * (c * n_coupon + S_T / S_0 - 1))'}]}]},
 '9.25': {'identity': {'product_id': '9.25', 'name_zh': '保底DCN', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'Hc': 80.0,
                    'c': 0.006,
                    'F': 0.8,
                    'Oc': 'monthly_last',
                    'Llock': 3,
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= schedule_levels(S_t[O_out], H_out_j), n_lock)',
                                'n_coupon': 'count_until(S_t[O_c] >= H_c, first_time_after(S_t[O_out] >= schedule_levels(S_t[O_out], H_out_j), n_lock))'},
                    'derived_terms': {'G': 'N * g',
                                      'ko_barrier_schedule': '[(1, S_0), (2, S_0), (3, S_0), (4, S_0), (5, S_0), (6, S_0), (7, S_0), (8, S_0), (9, S_0), (10, S_0), (11, S_0), (12, 0.8 * S_0)]'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['g == 0.2', 'F == 0.8', 'H_c == F * S_0', 'T == 1', 'n_lock < 12', 'is_monthly_schedule(O_out)', 'is_monthly_schedule(O_c)',
                                    'schedule_matches_ratios(H_out_j, S_0, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.8])']},
          'paths': [{'condition': 'tau_out < T',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * n_coupon)'}]},
                    {'condition': 'tau_out == T',
                     'cases': [{'domain': 'S_T >= H_c', 'pnl': 'cash(T, N * c * n_coupon)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * (c * n_coupon + max(S_T / S_0 - 1, F - 1)))'}]}]},
 '9.26': {'identity': {'product_id': '9.26', 'name_zh': '触发器', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.5,
                    'N': 2400000.0,
                    'g': 0.3,
                    'K': 100.0,
                    'H_KO': 103.0,
                    'H_KI': 80.0,
                    'O_KO': 'monthly_last',
                    'O_KI': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'r_out': 0.08,
                    'r_mat': 0.08,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)',
                                'tau_in': 'first_time(S_t[O_in] <= H_in)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K == S_0', 'H_in < H_out', 'is_monthly_schedule(O_out)']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * r_out)'}]},
                    {'condition': 'tau_out == inf and tau_in == inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(T, N * r_mat)'}]},
                    {'condition': 'tau_out == inf and tau_in < inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, 0)'},
                               {'domain': '0 <= S_T < K', 'pnl': 'cash(T, N * (S_T / K - 1))'}]}]},
 '9.27': {'identity': {'product_id': '9.27', 'name_zh': '锁盈缓冲结构', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 10000000.0,
                    'g': 0.2,
                    'H_KO': 103.0,
                    'c': 0.2,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': True,
                    'Bbuf': 80.0,
                    'monitor': {'tau_out': 'first_time_before(S_t[O_out] >= H_out, T)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['is_monthly_schedule(O_out)']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= K_buf', 'pnl': 'cash(T, N * (S_T - K_buf) / S_0)'},
                               {'domain': '0 <= S_T < K_buf', 'pnl': 'cash(T, N * (S_T / S_0 - 1))'}]}]},
 '9.28': {'identity': {'product_id': '9.28', 'name_zh': '限损票息结构', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.5,
                    'N': 10000000.0,
                    'g': 0.05,
                    'H_KO': 103.0,
                    'c': 0.117,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'Lmax': 0.05,
                    'Llock': 1,
                    'monitor': {'tau_out': 'first_time_after(S_t[O_out] >= H_out, n_lock)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out == 1.03 * S_0', 'is_monthly_schedule(O_out)']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * c * tau_out)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= S_0', 'pnl': 'cash(T, 0)'},
                               {'domain': '(1 - ell) * S_0 <= S_T < S_0', 'pnl': 'cash(T, N * r_T)'},
                               {'domain': '0 <= S_T < (1 - ell) * S_0', 'pnl': 'cash(T, -N * ell)'}]}]},
 '9.29': {'identity': {'product_id': '9.29', 'name_zh': '助推器', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 1.0,
                    'N': 5000000.0,
                    'g': 0.2,
                    'K': 100.0,
                    'H_KO': 103.0,
                    'O_KO': 'monthly_last',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'r_out': 0.09,
                    'alpha': 3.0,
                    'Lmax': 0.2,
                    'monitor': {'tau_out': 'first_time(S_t[O_out] >= H_out)'},
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['g == 0.2', 'K == S_0', 'H_out == 1.03 * S_0']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(tau_out, N * r_out)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'S_T >= K', 'pnl': 'cash(T, N * alpha * r_T)'},
                               {'domain': '(1 - ell) * S_0 <= S_T < K', 'pnl': 'cash(T, N * r_T)'},
                               {'domain': '0 <= S_T < (1 - ell) * S_0', 'pnl': 'cash(T, -N * ell)'}]}]},
 '10.1': {'identity': {'product_id': '10.1', 'name_zh': 'Worst-Of香草看涨期权', 'entry_status': True},
          'terms': {'S0Vec': [100.0, 100.0],
                    'T': 0.08333333333333333,
                    'K': 100.0,
                    'N': 1.0,
                    'p': 0.0159,
                    'exercise_style': 'European',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'pricing_methods': ['monte_carlo']},
          'paths': [{'condition': 'True',
                     'cases': [{'domain': '0 <= W_T <= K', 'pnl': 'cash(0, -N * p)'},
                               {'domain': 'W_T > K', 'pnl': 'cash(0, -N * p) + cash(T, N * (W_T - K) / 100)'}]}]},
 '10.2': {'identity': {'product_id': '10.2', 'name_zh': '折价看涨8080（保证金）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.08333333333333333,
                    'exercise_style': 'European',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'N': 10000000.0,
                    'g': 0.2,
                    'p': 0.0,
                    'K1': 80.0,
                    'K2': 100.0,
                    'alpha': 0.8,
                    'derived_terms': {'G': 'N * g'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K_1 < K_2', 'K_2 == S_0', 'p == 0']},
          'paths': [{'condition': 'True',
                     'cases': [{'domain': 'S_T > K_2', 'pnl': 'cash(T, N * alpha * r_T)'},
                               {'domain': 'K_1 < S_T <= K_2', 'pnl': 'cash(T, N * r_T)'},
                               {'domain': '0 <= S_T <= K_1', 'pnl': 'cash(T, -N * (S_0 - K_1) / S_0)'}]}]},
 '10.3': {'identity': {'product_id': '10.3', 'name_zh': '折价看涨8080（期权费）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.08333333333333333,
                    'exercise_style': 'European',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                    'N': 10000000.0,
                    'K1': 80.0,
                    'K2': 100.0,
                    'alpha': 0.8,
                    'p': 0.2,
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K_1 < K_2', 'K_2 == S_0', 'p == (S_0 - K_1) / S_0']},
          'paths': [{'condition': 'True',
                     'cases': [{'domain': 'S_T > K_2', 'pnl': 'cash(T, N * alpha * r_T)'},
                               {'domain': 'K_1 < S_T <= K_2', 'pnl': 'cash(T, N * r_T)'},
                               {'domain': '0 <= S_T <= K_1',
                                'pnl': 'cash(T, -N * (S_0 - K_1) / S_0)'}]}]},
 '10.4': {'identity': {'product_id': '10.4', 'name_zh': '方差互换', 'entry_status': True},
          'terms': {'T': 0.08333333333333333,
                    'Ksig': 13.0,
                    'Nvar': 2500.0,
                    'annualization_days': 244,
                    'Ovar': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                    'margin_call': False,
                    'derived_terms': {'Nvega': '2 * N_V * K',
                                      'G': 'max(0.1 * K * N_Vega, 3 * N_Vega)'},
                    'monitor': {'sigma_realized': '(realized_variance(S_t[O_var], n_ann) * 10000) ** 0.5'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ["O_var == 'daily'", 'n_ann == 244']},
          'paths': [{'condition': 'True',
                     'cases': [{'domain': 'sigma_realized >= 0',
                                'pnl': 'cash(T, N_V * (sigma_realized ** 2 - K ** 2))'}]}]},
 '10.5': {'identity': {'product_id': '10.5', 'name_zh': '看涨鲨鱼鳍（UOC）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.5,
                    'N': 10000000.0,
                    'K': 100.0,
                    'H_KO': 110.0,
                    'eta': 0.05,
                    'p': 0.026,
                    'O_KO': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out': 'first_time(S_t[O_out] >= H_out)'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['K < H_out']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -N * p) + cash(tau_out, N * r_out)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'K < S_T < H_out', 'pnl': 'cash(0, -N * p) + cash(T, N * (S_T - K) / S_0)'},
                               {'domain': '0 <= S_T <= K', 'pnl': 'cash(0, -N * p)'}]}]},
 '10.6': {'identity': {'product_id': '10.6', 'name_zh': '看跌鲨鱼鳍（DOP）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.5,
                    'N': 10000000.0,
                    'K': 100.0,
                    'H_KO': 90.0,
                    'eta': 0.05,
                    'p': 0.03,
                    'O_KO': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out': 'first_time(S_t[O_out] <= H_out)'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out < K']},
          'paths': [{'condition': 'tau_out < inf',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -N * p) + cash(tau_out, N * r_out)'}]},
                    {'condition': 'tau_out == inf',
                     'cases': [{'domain': 'H_out < S_T < K', 'pnl': 'cash(0, -N * p) + cash(T, N * (K - S_T) / S_0)'},
                               {'domain': 'S_T >= K', 'pnl': 'cash(0, -N * p)'}]}]},
 '10.7': {'identity': {'product_id': '10.7', 'name_zh': '双边鲨鱼鳍', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.16666666666666666,
                    'N': 10000000.0,
                    'Ku': 105.0,
                    'Kd': 95.0,
                    'H_KO_2': 115.0,
                    'H_KO_1': 85.0,
                    'eta_u': 0.03,
                    'eta_d': 0.04,
                    'alpha_u': 0.5,
                    'alpha_d': 0.8,
                    'p': 0.0088,
                    'O_KO': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'monitor': {'terminal_out_observed': 'require_maturity_observation(S_t[O_out], T)',
                               'tau_out_2': 'first_time(S_t[O_out] >= H_out_2)',
                               'tau_out_1': 'first_time(S_t[O_out] <= H_out_1)'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['H_out_1 < K_1 and K_1 < K_2 and K_2 < H_out_2']},
          'paths': [{'condition': 'tau_out_2 < tau_out_1',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -N * p) + cash(tau_out_2, N * r_out_2)'}]},
                    {'condition': 'tau_out_1 < tau_out_2',
                     'cases': [{'domain': 'S_T >= 0', 'pnl': 'cash(0, -N * p) + cash(tau_out_1, N * r_out_1)'}]},
                    {'condition': 'tau_out_2 == inf and tau_out_1 == inf',
                     'cases': [{'domain': 'K_2 <= S_T < H_out_2',
                                'pnl': 'cash(0, -N * p) + cash(T, N * alpha_2 * (S_T - K_2) / S_0)'},
                               {'domain': 'H_out_1 < S_T <= K_1',
                                'pnl': 'cash(0, -N * p) + cash(T, N * alpha_1 * (K_1 - S_T) / S_0)'},
                               {'domain': 'K_1 < S_T < K_2', 'pnl': 'cash(0, -N * p)'}]}]},
 '10.8': {'identity': {'product_id': '10.8', 'name_zh': '区间计息（Range Accrual）', 'entry_status': True},
          'terms': {'S0': 100.0,
                    'T': 0.08333333333333333,
                    'N': 10000000.0,
                    'Hlow': 94.0,
                    'Hup': 106.0,
                    'c_max': 0.0145,
                    'p': 0.0121,
                    'n_obs': 22,
                    'Orange': 'daily',
                    'settlement': 'cash',
                   'observation_price': 'close',
                   'margin_call': False,
                   'payoff_figure_basis': 'gross_before_premium',
                    'monitor': {'n_obs_actual': 'exact_observation_count(S_t[O_range], n_obs)',
                                'n_in': 'count(S_t[O_range] >= L and S_t[O_range] <= U)'},
                    'pricing_methods': ['monte_carlo'],
                    'constraints': ['L < U']},
          'paths': [{'condition': 'True',
                     'cases': [{'domain': 'n_in == n_obs', 'pnl': 'cash(0, -N * p) + cash(T, N * c_max)'},
                               {'domain': '0 < n_in < n_obs',
                                'pnl': 'cash(0, -N * p) + cash(T, N * c_max * n_in / n_obs)'},
                               {'domain': 'n_in == 0', 'pnl': 'cash(0, -N * p)'}]}]}}

REGISTRY = {
    "term_catalog": TERM_CATALOG,
    "products": PRODUCTS,
}
