"""Payoffer本机服务配置。默认资产不属于运行配置。"""

from __future__ import annotations

HOST = "127.0.0.1"
DEFAULT_PORT = 4181
PORT_ENV = "OPTIONHELPER_PAYOFF_PYTHON_PORT"
DEFAULT_MAINTENANCE_ENV = "OPTIONHELPER_PAYOFFER_DEFAULT_MAINTENANCE"

__all__ = ("HOST", "DEFAULT_PORT", "PORT_ENV", "DEFAULT_MAINTENANCE_ENV")
